-- Philip's Personal LinkedIn AI Agent - Initial Schema
-- Run in Supabase SQL Editor

create extension if not exists pgcrypto;

-- Enums
create type draft_status as enum (
  'pending',
  'approved',
  'sent_manually',
  'sent_via_authorized_api',
  'rejected',
  'expired'
);

create type interaction_kind as enum (
  'connection',
  'incoming_message',
  'outgoing_message',
  'follow_up',
  'note'
);

-- Contacts: people you know and professional context you choose to retain
create table contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  linkedin_member_id text,
  profile_url text,
  full_name text,
  headline text,
  relationship_notes text,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index contacts_member_unique
on contacts(user_id, linkedin_member_id)
where linkedin_member_id is not null;

create index contacts_user_idx on contacts(user_id);
create index contacts_created_idx on contacts(created_at desc);

-- Interactions: conversation events and notes, with deduplication
create table interactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  contact_id uuid not null references contacts(id) on delete cascade,
  kind interaction_kind not null,
  source text not null,
  external_event_id text,
  occurred_at timestamptz,
  content text,
  summary text,
  created_at timestamptz not null default now()
);

create unique index interaction_event_unique
on interactions(user_id, source, external_event_id)
where external_event_id is not null;

create index interactions_contact_idx on interactions(contact_id, created_at desc);
create index interactions_user_idx on interactions(user_id);

-- Drafts: messages generated by agent, approval state, sending status
create table drafts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  contact_id uuid not null references contacts(id) on delete cascade,
  interaction_id uuid references interactions(id) on delete set null,
  purpose text not null,
  draft_text text not null,
  status draft_status not null default 'pending',
  requires_approval boolean not null default true,
  approved_at timestamptz,
  sent_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index drafts_user_status_idx on drafts(user_id, status, created_at desc);
create index drafts_contact_idx on drafts(contact_id);

-- Followups: when and why you want to reconnect
create table followups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  contact_id uuid not null references contacts(id) on delete cascade,
  due_at timestamptz not null,
  reason text not null,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create index followups_due_idx on followups(user_id, due_at) where status = 'open';

-- Agent runs: workflow execution status and troubleshooting summaries
create table agent_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  workflow_name text not null,
  status text not null,
  input_summary jsonb,
  output_summary jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index agent_runs_user_idx on agent_runs(user_id, started_at desc);

-- Integration connections: provider and granted-scope metadata, not raw tokens
create table integration_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  provider text not null,
  scopes text[] not null default '{}',
  connection_status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- RLS: Enable but allow service_role full access. For MVP single-user, we use service role in backend.
alter table contacts enable row level security;
alter table interactions enable row level security;
alter table drafts enable row level security;
alter table followups enable row level security;
alter table agent_runs enable row level security;
alter table integration_connections enable row level security;

-- Create policies for service_role (bypass RLS) and anon for demo
-- In production, replace with proper auth.uid() checks

create policy "Allow all for service role"
on contacts for all
using (true)
with check (true);

create policy "Allow all for service role"
on interactions for all
using (true)
with check (true);

create policy "Allow all for service role"
on drafts for all
using (true)
with check (true);

create policy "Allow all for service role"
on followups for all
using (true)
with check (true);

create policy "Allow all for service role"
on agent_runs for all
using (true)
with check (true);

create policy "Allow all for service role"
on integration_connections for all
using (true)
with check (true);

-- Seed: Philip's user id placeholder (replace with actual auth user id if using Supabase Auth)
-- For MVP without auth, we use text 'philip' as user_id, but uuid column expects uuid.
-- So we will use a fixed uuid for Philip: 00000000-0000-0000-0000-000000000001
-- Insert sample contacts for testing (optional)

-- Function to update updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_contacts_updated_at before update on contacts
for each row execute function update_updated_at_column();

create trigger update_integration_connections_updated_at before update on integration_connections
for each row execute function update_updated_at_column();
