"use client";
import { useEffect, useState } from 'react';
import StatCard from '@/components/StatCard';
import { Users, MessageSquare, Inbox, Clock, Sparkles, ArrowRight, Copy, Check, Send } from 'lucide-react';
import Link from 'next/link';

interface Draft {
  id: string;
  draft_text: string;
  purpose: string;
  status: string;
  created_at: string;
  contacts?: { full_name: string; headline: string };
}

export default function Dashboard() {
  const [stats, setStats] = useState({ contacts: 0, drafts: 0, pending: 0, followups: 0 });
  const [recentDrafts, setRecentDrafts] = useState<Draft[]>([]);
  const [briefing, setBriefing] = useState<any>(null);
  const [loadingBriefing, setLoadingBriefing] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  useEffect(() => {
    fetchStats();
    fetchRecentDrafts();
  }, []);

  async function fetchStats() {
    try {
      const res = await fetch('/api/health');
      const health = await res.json();
      // Mock stats for now - in production fetch from supabase
      setStats({
        contacts: 12,
        drafts: 8,
        pending: 3,
        followups: 2
      });
    } catch (e) {
      console.error(e);
    }
  }

  async function fetchRecentDrafts() {
    // Mock drafts for demo UI - real data comes from Supabase
    setRecentDrafts([
      {
        id: '1',
        draft_text: 'Hey Sarah! Thanks for connecting — saw your work in AI infra at Stripe and it resonated. I\'ve been building AI agents and automation at Phoslab, curious what you\'re focused on these days?',
        purpose: 'welcome',
        status: 'pending',
        created_at: new Date().toISOString(),
        contacts: { full_name: 'Sarah Chen', headline: 'AI Infra @ Stripe' }
      },
      {
        id: '2',
        draft_text: 'Thanks for reaching out! That collaboration idea sounds interesting — I\'d love to learn more about what you have in mind. What kind of partnership are you thinking about?',
        purpose: 'reply_collaboration',
        status: 'pending',
        created_at: new Date(Date.now() - 3600000).toISOString(),
        contacts: { full_name: 'David Okafor', headline: 'Founder @ BuildLab' }
      }
    ]);
  }

  async function generateBriefing() {
    setLoadingBriefing(true);
    try {
      const res = await fetch('/api/agent/briefing', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: 'philip', timezone: 'Africa/Lagos' })
      });
      const data = await res.json();
      setBriefing(data.briefing);
    } catch (e) {
      console.error(e);
    } finally {
      setLoadingBriefing(false);
    }
  }

  function copyDraft(text: string, id: string) {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-[28px] font-semibold tracking-tight">Good morning, Philip</h1>
          <p className="text-[14px] text-white/50 mt-1">Your personal relationship assistant • {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })} • Africa/Lagos</p>
        </div>
        <button
          onClick={generateBriefing}
          disabled={loadingBriefing}
          className="px-4 py-2.5 rounded-xl bg-white text-black text-[13px] font-medium flex items-center gap-2 hover:bg-white/90 transition"
        >
          <Sparkles size={14} />
          {loadingBriefing ? 'Generating...' : 'Generate Briefing'}
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        <StatCard label="Total Contacts" value={stats.contacts} sub="Relationship memory" icon={Users} trend="+2 this week" />
        <StatCard label="Pending Drafts" value={stats.pending} sub="Needs your approval" icon={Inbox} />
        <StatCard label="Total Drafts" value={stats.drafts} sub="Generated by agent" icon={MessageSquare} />
        <StatCard label="Follow-ups" value={stats.followups} sub="Due this week" icon={Clock} />
      </div>

      <div className="grid grid-cols-3 gap-6">
        {/* Morning Briefing Card */}
        <div className="col-span-2 glass rounded-[20px] p-6">
          <div className="flex items-center justify-between mb-5">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-amber-500 to-orange-600 flex items-center justify-center">☀️</div>
              <div>
                <h2 className="text-[15px] font-semibold">Morning Briefing</h2>
                <p className="text-[11px] text-white/40">08:00 Africa/Lagos • Daily</p>
              </div>
            </div>
            <span className="text-[10px] px-2.5 py-1 rounded-full bg-white/5 border border-white/10 text-white/50">MIXED AUTONOMY</span>
          </div>

          {briefing ? (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5">
                <p className="text-[13px] text-white/80 leading-relaxed">{briefing.summary}</p>
                <p className="text-[11px] text-white/30 mt-2">{briefing.contacts_reviewed} contacts reviewed • {new Date(briefing.generated_at).toLocaleTimeString()}</p>
              </div>
              {briefing.items?.map((item: any, idx: number) => (
                <div key={idx} className="p-4 rounded-xl bg-white/[0.04] border border-white/5">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-[10px] px-2 py-1 rounded-full bg-blue-500/20 text-blue-300 border border-blue-500/20">{item.reason}</span>
                    <span className="text-[11px] text-white/40">→ {item.contact_id.slice(0,8)}</span>
                  </div>
                  <p className="text-[13px] text-white/70 leading-relaxed">{item.draft}</p>
                  <p className="text-[11px] text-white/30 mt-2">{item.context_summary}</p>
                </div>
              ))}
            </div>
          ) : (
            <div className="py-12 text-center">
              <div className="w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center mx-auto mb-3">🌅</div>
              <p className="text-[13px] text-white/60">No briefing generated yet today</p>
              <p className="text-[11px] text-white/30 mt-1 max-w-[320px] mx-auto">Generate your morning briefing to see who to reconnect with, personalized drafts, and follow-up reminders.</p>
              <button onClick={generateBriefing} className="mt-4 text-[12px] px-3 py-1.5 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 transition">
                Generate now →
              </button>
            </div>
          )}
        </div>

        {/* Architecture */}
        <div className="glass rounded-[20px] p-6">
          <h3 className="text-[13px] font-semibold mb-4">Architecture</h3>
          <div className="space-y-3 text-[11px]">
            <div className="flex gap-3">
              <div className="w-7 h-7 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">in</div>
              <div>
                <div className="text-white/80 font-medium">LinkedIn Account</div>
                <div className="text-white/30 leading-relaxed">OAuth-authorized access, manual intake fallback</div>
              </div>
            </div>
            <div className="ml-3.5 w-px h-4 bg-white/10" />
            <div className="flex gap-3">
              <div className="w-7 h-7 rounded-lg bg-violet-500/10 border border-violet-500/20 flex items-center justify-center shrink-0">n8n</div>
              <div>
                <div className="text-white/80 font-medium">n8n Orchestration</div>
                <div className="text-white/30 leading-relaxed">Schedules • Webhooks • Routing</div>
              </div>
            </div>
            <div className="ml-3.5 w-px h-4 bg-white/10" />
            <div className="flex gap-3">
              <div className="w-7 h-7 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center shrink-0">AI</div>
              <div>
                <div className="text-white/80 font-medium">Python Agent (Next.js API)</div>
                <div className="text-white/30 leading-relaxed">LLM + personal knowledge + policy gate</div>
              </div>
            </div>
            <div className="ml-3.5 w-px h-4 bg-white/10" />
            <div className="flex gap-3">
              <div className="w-7 h-7 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center shrink-0">DB</div>
              <div>
                <div className="text-white/80 font-medium">Supabase Memory</div>
                <div className="text-white/30 leading-relaxed">Contacts • Drafts • Follow-ups</div>
              </div>
            </div>
          </div>

          <div className="mt-6 p-3 rounded-xl bg-amber-500/10 border border-amber-500/20">
            <p className="text-[11px] text-amber-200/80 leading-relaxed">
              <strong>Important:</strong> Fully automatic messaging is disabled by default. All drafts require your approval unless explicitly authorized.
            </p>
          </div>
        </div>
      </div>

      {/* Pending Approval Inbox Preview */}
      <div className="glass rounded-[20px] p-6">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <h2 className="text-[15px] font-semibold">Approval Inbox</h2>
            <span className="text-[11px] px-2 py-0.5 rounded-full bg-white text-black font-medium">{recentDrafts.length} pending</span>
          </div>
          <Link href="/drafts" className="text-[12px] text-white/50 hover:text-white flex items-center gap-1">
            View all <ArrowRight size={12} />
          </Link>
        </div>

        <div className="grid grid-cols-2 gap-4">
          {recentDrafts.map(draft => (
            <div key={draft.id} className="p-4 rounded-xl bg-white/[0.03] border border-white/5 card-hover">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-violet-600 flex items-center justify-center text-[11px] font-bold">
                    {draft.contacts?.full_name.split(' ').map(n => n[0]).join('').slice(0,2)}
                  </div>
                  <div>
                    <div className="text-[13px] font-medium leading-none">{draft.contacts?.full_name}</div>
                    <div className="text-[11px] text-white/40 mt-1">{draft.contacts?.headline}</div>
                  </div>
                </div>
                <span className="text-[10px] px-2 py-1 rounded-full bg-amber-500/10 text-amber-300 border border-amber-500/20">
                  {draft.purpose}
                </span>
              </div>
              <p className="text-[13px] text-white/70 leading-relaxed bg-white/[0.02] p-3 rounded-xl border border-white/[0.03]">
                {draft.draft_text}
              </p>
              <div className="flex items-center gap-2 mt-3">
                <button
                  onClick={() => copyDraft(draft.draft_text, draft.id)}
                  className="flex-1 py-2 rounded-xl bg-white/5 border border-white/10 text-[12px] flex items-center justify-center gap-1.5 hover:bg-white/10 transition"
                >
                  {copiedId === draft.id ? <Check size={12} /> : <Copy size={12} />}
                  {copiedId === draft.id ? 'Copied!' : 'Copy draft'}
                </button>
                <button className="px-3 py-2 rounded-xl bg-white text-black text-[12px] flex items-center gap-1.5 font-medium hover:bg-white/90">
                  <Send size={12} /> Open LinkedIn
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Workflows */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { title: 'Morning Briefing', desc: '8:00 AM daily review of conversations and follow-ups', status: 'Ready', color: 'emerald' },
          { title: 'New Connection Welcome', desc: 'Personalized welcome when new person connects', status: 'Needs event source', color: 'blue' },
          { title: 'Reply Assistant', desc: 'Understand reply, suggest response in your voice', status: 'Ready', color: 'violet' },
        ].map(w => (
          <div key={w.title} className="glass rounded-2xl p-4">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-[13px] font-medium">{w.title}</h4>
              <span className={`text-[10px] px-2 py-0.5 rounded-full border ${
                w.color === 'emerald' ? 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' :
                w.color === 'blue' ? 'bg-blue-500/10 text-blue-300 border-blue-500/20' :
                'bg-violet-500/10 text-violet-300 border-violet-500/20'
              }`}>{w.status}</span>
            </div>
            <p className="text-[11px] text-white/40 leading-relaxed">{w.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
